// Auto-generated word-timing data for the CSE DevLabs promo voiceover.
// scene: which sentence/scene the word belongs to
// start/duration: frame offsets at 30fps, derived from word length + punctuation pauses,
// normalized to the real voiceover duration (48.75s).
export type WordBeat = {
  scene: number;
  word: string;
  start: number;
  duration: number;
  emphasis: boolean;
  sentenceEnd: boolean;
};

export const WORD_BEATS: WordBeat[] = [
  { scene: 0, word: "Struggling", start: 0, duration: 23, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "to", start: 23, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "find", start: 30, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "a", start: 39, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "final-year", start: 46, duration: 20, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "CSE", start: 66, duration: 7, emphasis: true, sentenceEnd: false },
  { scene: 0, word: "project", start: 73, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "that", start: 89, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "actually", start: 98, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "stands", start: 116, duration: 14, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "out", start: 130, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "to", start: 137, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "your", start: 144, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "professors", start: 153, duration: 23, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "and", start: 176, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 0, word: "recruiters?", start: 183, duration: 43, emphasis: false, sentenceEnd: true },
  { scene: 1, word: "Welcome", start: 226, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "to", start: 242, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "CSE", start: 249, duration: 7, emphasis: true, sentenceEnd: false },
  { scene: 1, word: "DevLabs!", start: 256, duration: 36, emphasis: true, sentenceEnd: true },
  { scene: 1, word: "We", start: 292, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "help", start: 299, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "computer", start: 308, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "science", start: 326, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "students", start: 342, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "bridge", start: 360, duration: 14, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "the", start: 374, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "gap", start: 381, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "between", start: 388, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "academic", start: 404, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "submissions", start: 422, duration: 25, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "and", start: 447, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "real-world,", start: 454, duration: 32, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "industry-grade", start: 486, duration: 29, emphasis: false, sentenceEnd: false },
  { scene: 1, word: "software.", start: 515, duration: 38, emphasis: false, sentenceEnd: true },
  { scene: 2, word: "Whether", start: 553, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "you're", start: 569, duration: 11, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "building", start: 580, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "in", start: 598, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "Artificial", start: 605, duration: 23, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Intelligence,", start: 628, duration: 38, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Machine", start: 666, duration: 16, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Learning,", start: 682, duration: 29, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Neural", start: 711, duration: 14, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Networks,", start: 725, duration: 29, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Blockchain,", start: 754, duration: 34, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Cybersecurity,", start: 788, duration: 41, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Big", start: 829, duration: 7, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Data", start: 836, duration: 9, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Analytics,", start: 845, duration: 32, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "or", start: 877, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "Cross-Platform", start: 884, duration: 29, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Mobile", start: 913, duration: 13, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "Apps—", start: 926, duration: 20, emphasis: true, sentenceEnd: false },
  { scene: 2, word: "we", start: 946, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "provide", start: 953, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "complete", start: 969, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "end-to-end", start: 987, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "technical", start: 1005, duration: 20, emphasis: false, sentenceEnd: false },
  { scene: 2, word: "execution.", start: 1025, duration: 41, emphasis: false, sentenceEnd: true },
  { scene: 3, word: "From", start: 1066, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "project", start: 1075, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "architecture", start: 1091, duration: 27, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "and", start: 1118, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "source", start: 1125, duration: 13, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "code", start: 1138, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "to", start: 1147, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "research", start: 1154, duration: 18, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "paper", start: 1172, duration: 11, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "publication—", start: 1183, duration: 36, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "we've", start: 1219, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "got", start: 1228, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "you", start: 1235, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "covered.", start: 1242, duration: 36, emphasis: false, sentenceEnd: true },
  { scene: 3, word: "Fill", start: 1278, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "out", start: 1287, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "the", start: 1294, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "form", start: 1301, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "below", start: 1310, duration: 11, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "or", start: 1321, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "contact", start: 1328, duration: 16, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "CSE", start: 1344, duration: 7, emphasis: true, sentenceEnd: false },
  { scene: 3, word: "DevLabs", start: 1351, duration: 16, emphasis: true, sentenceEnd: false },
  { scene: 3, word: "today", start: 1367, duration: 11, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "to", start: 1378, duration: 7, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "kickstart", start: 1385, duration: 20, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "your", start: 1405, duration: 9, emphasis: false, sentenceEnd: false },
  { scene: 3, word: "project!", start: 1414, duration: 36, emphasis: false, sentenceEnd: true },
];

export const SCENE_LABELS = [
  "hook",
  "intro",
  "capabilities",
  "cta",
];

export const WORDS_END_FRAME = 1450;
